trigger: container_create
args: image,privileged,binds,capadd
cmd: main.sh          #use build in authz to do action. lala
onerrorallow: false
metadata: whitelist,privileged
desc: check the container request 
